In [7]:
import numpy as np

class DataPreprocessor():
    def __init__(self,strategy='mean'):
        self.strategy = strategy
        self.fill_values = None
        self.mean_ = None
        self.std_ = None

    def fit(self,X):
        if self.strategy =='mean':
            self.fill_values = np.nanmean(X,axis=0)
        if self.strategy =='median':
            self.fill_values = np.nanmedian(X,axis=0)
        if self.strategy =='0':
            self.fill_values = np.zeros(len(X[0]))

        self.mean_ = np.nanmean(X,axis=0).reshape(-1,1)
        print(self.mean_)
        self.std_ = np.nanstd(X,axis=0).reshape(-1,1)
        print(self.std_)
        
        return self
    
    def transform(self,X):
            X = X.T
            try:
                for j in range(len(X)):
                    idx = np.argwhere(np.isnan(X[j]))
                    X[j][idx] = self.fill_values[j]
                X = (X - self.mean_)/(self.std_)
                return X.T
            except:
                raise ValueError("fit wasn't called")
         
    
    def fit_transform(self,X):
        self.X = X 
        self = self.fit(X)

        X = X.T
        for j in range(len(X)):
            idx = np.argwhere(np.isnan(X[j]))
            X[j][idx] = self.fill_values[j]

        X = (X - self.mean_)/(self.std_)
        return X.T
    
    def summary(self):
        print(f" Mean for Each Column:\n{self.mean_}")
        print(f" Standard Deviation for Each Column :\n{self.std_}")
        print(f"The fit value for each column: \n{self.fill_values}")



In [8]:
np.random.seed(42)
X_train = np.array([
    [1.0, 2.0, np.nan],
    [np.nan, 3.5, 1.0],
    [2.5, np.nan, 2.0],
    [3.0, 4.0, 1.5],
    [np.nan, 2.5, np.nan],
])

X_test = np.array([
    [2.0, np.nan, 1.0],
    [np.nan, 3.0, np.nan],
])

preprocessor = DataPreprocessor(strategy='mean')

X_train_clean = preprocessor.fit_transform(X_train)

X_test_clean = preprocessor.transform(X_test)  

preprocessor.summary()

print("\nCleaned train:\n", X_train_clean.round(3))
print("Cleaned test:\n", X_test_clean.round(3))

[[2.16666667]
 [3.        ]
 [1.5       ]]
[[0.84983659]
 [0.79056942]
 [0.40824829]]
 Mean for Each Column:
[[2.16666667]
 [3.        ]
 [1.5       ]]
 Standard Deviation for Each Column :
[[0.84983659]
 [0.79056942]
 [0.40824829]]
The fit value for each column: 
[2.16666667 3.         1.5       ]

Cleaned train:
 [[-1.373 -1.265  0.   ]
 [ 0.     0.632 -1.225]
 [ 0.392  0.     1.225]
 [ 0.981  1.265  0.   ]
 [ 0.    -0.632  0.   ]]
Cleaned test:
 [[-0.196  0.    -1.225]
 [ 0.     0.     0.   ]]
